# Generated by Django 3.2.2 on 2021-06-04 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email',
            new_name='email_id',
        ),
    ]
