# Generated by Django 3.2.2 on 2021-06-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_email_userprofile_email_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email_id',
            new_name='email',
        ),
    ]
