# Generated by Django 3.2.2 on 2021-06-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='myrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalname', models.CharField(max_length=50)),
                ('doctorname', models.CharField(max_length=50)),
                ('hospitallocation', models.CharField(max_length=250)),
                ('diseasename', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('documentname', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='')),
                ('prescription', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
