# Generated by Django 3.2.2 on 2021-06-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_myrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrecord',
            name='email',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
