# Generated by Django 3.2.2 on 2021-06-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_myrecord_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescrip_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('diseasename', models.CharField(max_length=50)),
                ('medicinename', models.CharField(max_length=50)),
                ('meal', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
