# Generated by Django 3.2.2 on 2021-06-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_prescription_medicinename'),
    ]

    operations = [
        migrations.CreateModel(
            name='hadmin',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
